#### Vectore operations

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2])

In [3]:
print(vector)

[1 2]


In [4]:
#### Operations

In [7]:
vec1 = np.array([1,2])
vec2 = np.array([3,4])

vec1 + vec2

array([4, 6])

In [8]:
vec1 - vec2

array([-2, -2])

In [9]:
2*vec1

array([2, 4])

In [11]:
np.dot(vec1, vec2)

np.int64(11)